[build]
  publish = "."
  command = "node scripts/generate-hidden-form.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "18"

[[forms.notifications]]
  for = "registration"
  email = "monstros.consulting@gmail.com"

